### ISSUE TITLE
[Conflict/Crash] getSmoothColor divide by zero

### ISSUE THREAD

**Issue by An-Sar** [Liahim85/MistyWorld_Open#36]
This happens in a mod pack that i put together, and i was not able to reproduce the problem with only Mist installed. 

i am intending to try and narrow down the conflict a bit more, but figured i would at least open an issue incase you can see something right off that might be happening.
 
Also this only seems to effect single player, or possibly new worlds, as i was running the current version on a server without noticing the problem until i tried to switch to a single player world.

```
java.lang.ArithmeticException: / by zero
	at ru.liahim.mist.init.ItemColoring.getSmoothColor(ItemColoring.java:108)
	at ru.liahim.mist.init.ItemColoring.createFoodColorList(ItemColoring.java:83)
	at ru.liahim.mist.common.ClientProxy.createFoodColorList(ClientProxy.java:67)
	at ru.liahim.mist.handlers.ServerEventHandler.onPlayerLoggedIn(ServerEventHandler.java:567)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1112_ServerEventHandler_onPlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:574)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

[Full Crash Log](https://pastebin.com/MpL270QP)

**Comment by Liahim85** [comment]
It looks as if some food had an empty texture.
Fixed!

**Comment by An-Sar** [comment]
awesome!
