### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by VioletWyvern** [Liahim85/MistyWorld_Open#44]
This problem still bothering me,  Whenever I'm doing anything,  This crash always shows-up  :

Description: Initializing game

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1947)
	at ru.liahim.mist.item.ItemMistGenderNameBlock.func_77653_i(ItemMistGenderNameBlock.java:15)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$1012/15913501.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1014/196280688.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Liahim85** [comment]
Try to fix... Update.
