### ISSUE TITLE
ClassCastException in GenLayerBordersFinal while exploring Misty dimension

### ISSUE THREAD

**Issue by codewarrior0** [Liahim85/MistyWorld_Open#74]
MistyWorld-1.12.2-1.2.4.12.jar

Pack: [Heavens of Sorcery](https://www.curseforge.com/minecraft/modpacks/heavens-of-sorcery)

Crash occurs without any warning and has occurred ~twice~ three times so far. 

Seed: -4564884748250065798

https://pastebin.com/PxBCfg9A

```
Description: Exception generating new chunk
 
java.lang.ClassCastException: net.minecraft.world.biome.BiomeOcean cannot be cast to ru.liahim.mist.world.biome.BiomeMist
at ru.liahim.mist.world.layer.GenLayerBordersFinal.getBool(GenLayerBordersFinal.java:28)
at ru.liahim.mist.world.layer.GenLayerBorders.func_75904_a(GenLayerBorders.java:22)
at ru.liahim.mist.world.layer.GenLayerZoomMist.func_75904_a(GenLayerZoomMist.java:25)
at ru.liahim.mist.world.layer.GenLayerZoomMist.func_75904_a(GenLayerZoomMist.java:25)
at ru.liahim.mist.world.layer.GenLayerBorders.func_75904_a(GenLayerBorders.java:17)
at ru.liahim.mist.world.BiomeProviderMist.func_76937_a(BiomeProviderMist.java:85)
at ru.liahim.mist.world.ChunkProviderMist.setBlocksInChunk(ChunkProviderMist.java:139)
at ru.liahim.mist.world.ChunkProviderMist.func_185932_a(ChunkProviderMist.java:115)
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
```

**Comment by Liahim85** [comment]
Try this https://cloud.mail.ru/public/2WBx/2v3Y8vWiH

**Comment by Liahim85** [comment]
Please tell me if it works or not?
